services:
  - type: web
    name: fotokopiku
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: FotokopiKu
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: fotokopiku-db
          property: host
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        fromDatabase:
          name: fotokopiku-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: fotokopiku-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: fotokopiku-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie

databases:
  - name: fotokopiku-db
    databaseName: fotokopiku
    user: fotokopiku
    region: singapore
    plan: free
