CREATE DATABASE IF NOT EXISTS fotokopi1 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE fotokopi1;

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_name VARCHAR(200) NOT NULL,
  address TEXT,
  shipping TINYINT(1) DEFAULT 0,
  tracking_code VARCHAR(100) DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  total DECIMAL(10,2) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
